### ISSUE TITLE
Suggestion: hilight line

### ISSUE THREAD

**Issue by superaxander** [GopherAtl/edit-plus#10]
Ability to hilight a line(different background colors) the hilighted lines would be stored in the config or a seperate file for every file with hilighted lines

**Comment by GopherAtl** [comment]
I do not really understand the logic of this feature? I'm not seeing the utility of it.

**Comment by GopherAtl** [comment]
in any case, like bookmarks, it's a maybe for far down the road, as it would depend on having workspace files to store this kind of meta-information about files.
