### ISSUE TITLE
Suggestion: bookmarks

### ISSUE THREAD

**Issue by superaxander** [GopherAtl/edit-plus#11]
Ability to label certain lines and quick jump to them with dialog box. Also maybe jump from bookmark to bookmark in the order they exist in the file. The bookmarks can be stored in the configfile(or maybe a different file for each file with bookmarks

**Comment by GopherAtl** [comment]
something like this is in the tentative wishlist, if I ever decide to implement workspaces. But that's a maybe, possibly, multiple versions from now thing, and I'm trying to stick to more concrete, planned features for the repo's issues.

**Comment by GopherAtl** [comment]
I'll re-open this issue when and if I get as far as actually planning a workspace update.
