### ISSUE TITLE
Suggestion: debugger

### ISSUE THREAD

**Issue by superaxander** [GopherAtl/edit-plus#8]
line per line debugging. sample code to execute per line(with indentation removed):

``` lua
if line:sub(1,5) == "local" then
  --we found a local variable(problem non-local variables may not start with local because this will mess up when a variable has its value set
  --here you add the variable name to a table
  --from now on this variable name will be replaced by that name
  --track the variable's value
else
  --replace tracked variables with their temporary new names
end
--run the line and handle errors
ok, err = pcall(loadstring(line))
if not ok then
  --show error and mark the line at which it occured
end
```

Also the chosen temporary global variable names should be checked to not interfere with any other running program. (Maybe even sandbox the debugged program?) this would be a feature far far off.

**Comment by GopherAtl** [comment]
uhm. I appreciate the thought, but as I said in the pm where you suggested this the first time, it is far more complicated than you're making it sound. As I said in pm, I may, way down the road, tackle this, but it's not a firm enough plan for me to be adding it to the planned feature issues on the repo.
