### ISSUE TITLE
Suggestion: themes

### ISSUE THREAD

**Issue by superaxander** [GopherAtl/edit-plus#9]
Simple suggestion add themes(just load them from a folder in /etc or /usr/etc or bindir)

**Comment by GopherAtl** [comment]
not really a priority. Closes to themes I have considered is, maybe, configurable syntax hilighting. This kind of cosmetic change is just not enough of a priority for the time being. If it is ever implemented, it will be as a feature of guiutils, which I may fork into a separate project at some point, not a specific feature of edit+.
